package com.softdesign.devintensive.utils;

/**
 * Created by Роман on 23.06.2016.
 */
public interface ConstantManager {
    String TAG_PREFIX = "DEV_";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";
    String STAT_PANEL_PADDING_KEY = "STAT_PANEL_PADDING_KEY";

    int REQUEST_CAMERA_PHOTO = 100;
    int REQUEST_GALLERY_PICTURE = 101;
    int REQUEST_PERMISSION_CODE = 102;
    int CAMERA_REQUEST_PERMISSION_CODE = 103;
    int GALLERY_REQUEST_PERMISSION_CODE = 104;
    int REST_API_FAILURE_RESPONSE_CODE = 0;

    String AUTH_TOKEN = "AUTH_TOKEN";
    String USER_ID_KEY = "USER_ID";

    String USER_FULL_NAME = "USER_FULL_NAME";
    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_EMAIL_KEY = "USER_EMAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GITHUB_KEY = "USER_GITHUB_KEY";

    String USER_ABOUT_KEY = "USER_ABOUT_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String USER_AVATAR_KEY = "USER_AVA_KEY";

    String USER_PHOTO_DOWNLOAD_DATE_KEY = "USER_PHOTO_DOWNLOAD_DATE_KEY";
    String USER_RAITING_VALUE = "USER_RAITING_VALUE";
    String USER_CODE_LINES_COUNT = "USER_CODE_LINES_COUNT";

    String USER_PROJECT_VALUES = "USER_PROJECT_VALUES";
    String USER_AUTORIZATION_FAILED = "USER_AUTORIZATION_FAILED";

    String PARCELABLE_KEY = "PARCELABLE_KEY";
    String AUTH_CURRENT_LOGIN = "AUTH_CURRENT_LOGIN";
    String AUTH_AUTO_LOGIN_FLAG = "AUTH_AUTOLOGIN_FLAG";
}
